### ISSUE TITLE
Regexp support in elixir-lang

### ISSUE THREAD

**Issue by vdaniuk** [elixir-lang/language-elixir#38]
The regexp expression in elixir-lang is not detected as a regex by Atom and as a consequence regex packages like regex-railroad aren't activated. Simple example:
```
String.replace(~r/\s+/," ")
```

**Comment by keathley** [comment]
Looks like the issue is that its just matching all sigils as interpolated elixir strings.

**Comment by keathley** [comment]
I've opened a PR to handle this. Looks like some changes will need to be made to regex-railroad to correctly interpret elixir regex.
