### ISSUE TITLE
Snippets for inline def, defp

### ISSUE THREAD

**Issue by gusaiani** [elixir-lang/language-elixir#42]
In my own snippets file, I’ve been using snippets for inline `def` and `defp`, like this:

```
  'inline def':
    prefix: 'id'
    body: 'def $1, do: $2'

  'inline defp':
    prefix: 'idp'
    body: 'defp $1, do: $2'
```

I’ve been finding it a welcome addition, and wonder if this would make sense for more people.

**Comment by keathley** [comment]
I love this. I'd like to keep the prefixes semantically the same with the `def` and `defp` prefixes. Something like `idef` and `idefp`. If you want to open a PR with these changes that would be the best place to discuss it :+1:
