### ISSUE TITLE
Support highlighting TODO comments with language-todo

### ISSUE THREAD

**Issue by duien** [elixir-lang/language-elixir#45]
Currently, "TODO", "FIXME", etc. keywords are not highlighted inside of comments in Elixir. In order for the `language-todo` package to highlight those, the grammar for comments must use `begin`/`end` patterns instead of `match`. 

See atom/language-go@e5180ac for an example of the change that would need to be made.

I'll likely try to make a PR to fix this, but wanted to open an issue in the meantime so there's a record of what would need to be done.

**Comment by keathley** [comment]
Thanks for catching this @duien. I just noticed your note about submitting a PR. I was already in the process of fixing a few things and I skimmed over it :confused: 

If you want to check out the PR that I pushed up and let me know what you think that would be awesome.

**Comment by duien** [comment]
Thanks for fixing this! No worries at all about my planned PR -- I clearly hadn't gotten around to it :smiley: 

The fix is working great for me, so I'm happy!
