### ISSUE TITLE
Syntax recognition for Bitwise >>> and &&&

### ISSUE THREAD

**Issue by gusaiani** [elixir-lang/language-elixir#46]
This is, at least to me, a total edge case.

Working with Dave Thomas’ book, I came across code using the Bitwise macro.

There, `>>>` and `&&&` were not recognized as Elixir syntax, which in the case of `|>`, `<>` and many others prints a marvelous ligature if ligatures are enabled. I checked and FiraCode, the popular font with ligatures, does have those two ligatures in its set.

**Comment by keathley** [comment]
Thanks for catching this. I've opened a PR that should fix it if you want to check it out.
