### ISSUE TITLE
Case used as a variable being highlighted as a keyword

### ISSUE THREAD

**Issue by bjfish** [elixir-lang/language-elixir#53]
Note the difference in the key/values in the pattern match:

![screen shot 2016-04-04 at 2 44 38 pm](https://cloud.githubusercontent.com/assets/110023/14260956/d59a6908-fa73-11e5-999b-10a4a39dfe46.png)

**Comment by keathley** [comment]
So it looks like the `case` is matching too specifically. Which would mean that the other control structures have this same issue. I suspect that this can be fixed by matching on something like: `/case (.*)+ do/`.

**Comment by keathley** [comment]
@bjfish I've opened a PR that should solve this. Let me know what you think.

**Comment by keathley** [comment]
I'm closing this for now. Let me know if something still doesn't look correct.
