### ISSUE TITLE
prepending variable ending with do to a list breaks syntax highlighting

### ISSUE THREAD

**Issue by almightycouch** [elixir-lang/language-elixir#56]
Prepending a variable which name ends with `do` to a list, breaks the syntax highlighting:

```elixir
todos = [todo|todos]
```
<img width="518" alt="Screenshot" src="https://cloud.githubusercontent.com/assets/7694587/15023235/f71605c8-122f-11e6-9bd6-93e866223999.png">

**Comment by keathley** [comment]
Thanks for submitting this. I think I have a fix but I need to do a bit more testing and write some proper unit tests.
