### ISSUE TITLE
Sigils and syntax highlighting 

### ISSUE THREAD

**Issue by almightycouch** [elixir-lang/language-elixir#57]
I found a few issues with sigils and syntax highlighting.

* Sigils do not work with lowercase letters:

  <img width="161" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7694587/15024993/7bb021e0-1237-11e6-91a3-1bed3c4739c0.png">

* Sigils should only allow the 8 different delimiters:

  <img width="157" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7694587/15025125/127e6988-1238-11e6-9a55-186a8a0b4694.png">

* Sigils delimiters should not have the same color as their content (see screenshots).

**Comment by keathley** [comment]
Thanks for submitting this! Sigils have been one of the most complex pieces of the package. Let me know if you find any other edge cases.
