### ISSUE TITLE
Short `do:` block is not properly highlighted

### ISSUE THREAD

**Issue by armed** [elixir-lang/language-elixir#67]
`do:` with semicolon is highlighted as map/keyword key:
<img width="274" alt="screen shot 2016-06-05 at 3 01 27 pm" src="https://cloud.githubusercontent.com/assets/223060/15804547/898e9ab6-2b2e-11e6-8cfe-3e63157f6265.png">

**Comment by nii236** [comment]
The indentation also does work on a newline if you use `do` instead of `do:`

**Comment by keathley** [comment]
@armed: I'm not sure that this is a bug. In this case the do _is_ a keyword. Should we have a special case for `do:` as a keyword? My gut feeling is that we shouldn't.

@nii236: I'll take a look at this.

**Comment by nii236** [comment]
@keathley: Thanks! I added two gifs comparing `vim` and `atom` for your reference.

## Vim

![elixir_vim](https://cloud.githubusercontent.com/assets/4482567/15988811/e3cf53dc-3090-11e6-8b41-7ce643220b6c.gif)

## Atom

![elixir_atom](https://cloud.githubusercontent.com/assets/4482567/15988813/ecac1990-3090-11e6-98e1-543e9795ec70.gif)

**Comment by armed** [comment]
@keathley I got your point, but what confused me is that before commit 264ffbf528fcb3129c191d60d8aa22b6770d3449 `do:` along with `do` was highlighted as other keywords.

**Comment by nii236** [comment]
That's fine, I'll make a new issue

**Comment by keathley** [comment]
@armed Sorry for the confusion. I wish there was a better way to communicate these sorts of changes so people aren't surprised by them. It would be cool if atom pulled in release notes or something similar.
