### ISSUE TITLE
Unnecessary extra tab character after newlines for `do` keyword 

### ISSUE THREAD

**Issue by nii236** [elixir-lang/language-elixir#69]
Please see the gifs below:

## Vim

![elixir_vim](https://cloud.githubusercontent.com/assets/4482567/15988811/e3cf53dc-3090-11e6-8b41-7ce643220b6c.gif)

## Atom

![elixir_atom](https://cloud.githubusercontent.com/assets/4482567/15988813/ecac1990-3090-11e6-98e1-543e9795ec70.gif)

**Comment by keathley** [comment]
I'm not able to re-create this. Are there any other settings that I should be aware of?

**Comment by nii236** [comment]
Yeah! It turns that since I code a lot of Go, my tab were set to 8 spaces. I've set them to 2 spaces now and it's not behaving as expected. Thanks for getting back to me!

**Comment by keathley** [comment]
No problem. Sorry it took a while. You probably already know this but you can set language level tab lengths for each language package. I typically set them for things like ruby, go, or elixir where there is a standard tab length "style".
