### ISSUE TITLE
Erlang home configuration setting missing

### ISSUE THREAD

**Issue by LaughingBubba** [elixir-lang/language-elixir#71]
Hi, from time to time I get the above as a flash message in atom on Windows 10 (when editing elixir code)

The thing is, I do have erlang installed and the environment variable set up. I get the following when I do an env in the CLI ("..." meaning other environment variables)
~~~
...
ERLANG_HOME=C:\Program Files\erl7.2.1\bin
...
~~~

I also happen to have the erlang package installed in atom and it seems fine. Syntax checking and code completion are working fine for both languages.

Is there a config file I could update or something?

Thanks in advance.

**Comment by keathley** [comment]
We don't require any environment variables in this package. Its simply the highlighting for elixir grammars. Its probably another elixir package that you have installed.

**Comment by LaughingBubba** [comment]
Ah! Yes it was the [autocomplete-elixir](https://atom.io/packages/autocomplete-elixir) package which has a few open issues related to this.

I updated the (optional for windows) settings and that seems have done the trick.

Thanks!
