### ISSUE TITLE
Auto-complete will lose "?"

### ISSUE THREAD

**Issue by Ljzn** [elixir-lang/language-elixir#78]
language-elixir 0.16.0

example : 

`def is_true?, do: "yes"`

The auto-complete will show `is_true`

**Comment by keathley** [comment]
@Ljzn are you using any other plugins like autocomplete elixir or atom-elixir? I'll look into issues with autocomplete+ to see if there are any open issues.

**Comment by keathley** [comment]
Looks like this is an existing issue in autocomplete-plus: atom/autocomplete-plus/issues/715

**Comment by keathley** [comment]
Closing since this isn't related to this package.
