### ISSUE TITLE
keyword 

### ISSUE THREAD

**Issue by Euklidian-Space** [elixir-lang/language-elixir#88]

**Comment by Euklidian-Space** [comment]
Not  a huge issue, but the keyword 'in' doesn't get highlighted.  Anyone else experiencing this?

**Comment by keathley** [comment]
`in` is being marked as an operator correctly.

<img width="1287" alt="screen shot 2017-03-30 at 1 45 00 pm" src="https://cloud.githubusercontent.com/assets/1642095/24518258/501e2196-154f-11e7-955d-03ea28797da7.png">

The reason that `in`, `and`, and other operators aren't highlighted is that themes tend to use the base color for operators. We could mark operators as control structures but I'm not sure thats something we want to do. 

I'm going to close this for now. Feel free to re-open it if you feel strongly about it 😄.
